# -*- coding: utf-8 -*-
"""Aula03ControleAbacates.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MriR8zKhju2gNqmAbHO4d9aN0yPjs4VI
"""

!pip install pdf_reports -q \#pacote do python que gera pdf

#Fazer de acordo com aula 03
#Esta aula vai carregar um arquivo excel, gerar um odf de acordo com arquivo pug 
#depois atualizar no pdf com arquivo mais atualizado

# A cara do pdf esta neste arquivo .pug
import pandas as pd #importa biblioteca do panda para calculos
from datetime import datetime 
from pdf_reports import pug_to_html,write_report #biblioteca que gera pdf

planilha = pd.read_excel('/content/controle_de_abacates.xlsx')#carrega excel

planilha #imprime todo excel

#templates estao no arquivo.pug, este template tem no google e carlos adaptou

#joga a data de hoje na variavel hoje e depois imprime
hoje = datetime.now().date()
print(hoje)

#gera um pdf para a variavel html em que carrega o modelo df, e coloca planilha e hoje como se fosse variaveis que os valores
#irao alterar de acordo com estas duas variaveis. No Modelo html ja tem lugar em que a olanilhae dados geram graficos
# e o hj aparece no relatorio
html = pug_to_html("/content/modelo_de_relatorio.pug",
                   planilha = planilha,
                   hoje = hoje)

html#le a varviavel html que gerei o pug

#Converti para pdf
write_report(html,"controle_abacates_relatorios.pdf")

#Para atualizar com os dados novos controle de abacates atualizados e repetir acima porem mnudando a planilha

planilha = pd.read_excel('/content/controle_de_abacates_atualizado.xlsx')#carrega excel

#joga a data de hoje na variavel hoje e depois imprime
hoje = datetime.now().date()
print(hoje)

#gera um pdf para a variavel html em que carrega o modelo df, e coloca planilha e hoje como se fosse variaveis que os valores
#irao alterar de acordo com estas duas variaveis. No Modelo html ja tem lugar em que a olanilhae dados geram graficos
# e o hj aparece no relatorio
html = pug_to_html("/content/modelo_de_relatorio.pug",
                   planilha = planilha,
                   hoje = hoje)

#Converti para pdf - Fiz isso e agora atualizou os dados - So verificar os dois arquivos PDF abacate na pasta de estudos
write_report(html,"controle_abacates_relatorios.pdf")

