# -*- coding: utf-8 -*-
"""VideoIntroPandasCarlos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15gsy0iOD7cyFj3sPhxQejvVOX_AJ7MuX
"""

#importar biblioteca panda os as pd e criar um apelido para usar
import pandas as pd
#criar uma variavel - e colcoar o read csv com o caminho  Posso colocar direto do github
df = pd.read_csv('https://raw.githubusercontent.com/carlosfab/curso_data_science_na_pratica/master/modulo_02/BBAS3.SA.csv')

#com head verifico as primeras linhas
df.head()

#Shape conta as linhas e colunas  

df.shape

#seleciona dados da coluna isolada
df["Close"]

#Calcula media da coluna close. Quando quiser analisar uma coluna tem que ser totalmente igual - o nome da coluna e o que esta digitando
df["Close"].mean()

#retorna todas as colunas
df.columns

#desta forma abaixo podemos selecionar a coluna Open selecionando os 10 primeiras linhas
df.Open[0:10]

#aqui traz todo resumo estatitsico de todas as colunas. 
df.describe()

#calcular Mediana
df.Open.median()

#calcular Desvio Padrao
df.Open.std()

#calcular valor minimo
df.Open.min()

#Calcula valor Maximo
df.Open.max()

#criar um grafico de linhas
df['Open'].plot()

#criar um histrgrama para distribuicao dos dados da coluna Volume
df['Volume'].hist()

#cria um scaterplot para analisar as relações entre coluna low e high. dentro do paratense primeiro vem x depois y
df.plot.scatter('Low','High')

#cria um boxplot
df['High'].plot.box()

